version: "3.8"

services:
  backend:
    platform: linux/amd64  # Ensures correct architecture
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=${POSTGRES_PORT}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    depends_on:
#      postgres:
#        condition: service_healthy  # Waits for PostgreSQL to be ready
#    command: ["sh", "-c", "sleep 5 && node server.js"]  # Small delay before starting backend

#  postgres:
#    image: postgres:latest
#    restart: always
#    environment:
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    healthcheck:  # Ensure PostgreSQL is ready before backend starts
#      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

#volumes:
#  postgres_data:
